### ISSUE TITLE
Discussion regarding contributing in the project

### ISSUE THREAD

**Issue by nayan32biswas** [apocas/restai#77]
Hi @apocas,
I found the project very helpful and want to add some improvement to the project if you agree with the change.

## Issues

1. Loading environment variable is not organized.
2. docker-compose file is not configured properly to run the project.

I want to add those changes if you think those change will improve the project.

**Comment by apocas** [comment]
Great stuff @nayan32biswas 🙏 

Yes it definitely needs some love around those things :)

I'm going to merge https://github.com/apocas/restai/pull/78
