### ISSUE TITLE
Inquiry About Chat Loading Mechanism in ReAct Agent Code

### ISSUE THREAD

**Issue by mhsabu** [apocas/restai#89]
Hi,

I was going through your recent ReAct agent code. On my computer, this code cannot load chat history:

```python
chat = self.brain.memories.loadMemory(project.model.name).loadChat(chatModel)
```

Could you please explain how this chat loading works in your code? Additionally, are you able to give the agent chat history when the agent is answering the next question?

Thank you!

**Comment by apocas** [comment]
Chat was refactored since this issue was open.
Should be more clear now.
