### ISSUE TITLE
VISION project typ does not works with llava.

### ISSUE THREAD

**Issue by just-valera** [apocas/restai#92]
To work, you need to connect to open AI, but why?

**Comment by apocas** [comment]
It will be changed in the next version.
Vision was a bit forgotten unfortunately.

At the time there was no proper "multimodal", so... there was an agent coordinating stuff.

**Comment by apocas** [comment]
Fixed, vision projects are only completely focused on the selected vision LLM.

Pure image generation (Flux, SD, DallE, etc) was segregated.
https://apocas.github.io/restai/api.html#get-image-generators-list
